import com.example.beginningwithdrools.DecisionFact
import com.example.beginningwithdrools.Result
import com.example.beginningwithdrools.Utils

rule "Rule 1"
when
    DecisionFact(value1 == "val1")
    $res : Result()
then
    Utils.setResult($res, "decision one");
end

rule "Rule 2"
when
    DecisionFact(value1 == "val2")
    $res : Result()
then
    Utils.setResult($res, "decision two");
end

rule "Rule 3"
when
    DecisionFact(value1 == "val3")
    $res : Result()
then
    Utils.setResult($res, "decision three");
end

rule "Rule 4"
when
    DecisionFact(value1 == "val4")
    $res : Result()
then
    Utils.setResult($res, "decision four");
end

rule "Rule Default"
when
    DecisionFact(value1 == "val5")
    $res : Result()
then
    Utils.setResult($res, "decision default");
end